version: "3.9"

services:
  db:
    image: postgres:15
    container_name: math-db
    restart: always

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: mathsolver

    ports:
      - "5432:5432"

    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: .
    container_name: math-backend
    restart: always

    depends_on:
      - db

    environment:
      DATABASE_URL: ${DATABASE_URL}
      HF_API_KEY: ${HF_API_KEY}

    ports:
      - "8000:8000"

volumes:
  pgdata:
  